### PR TITLE
Sprint3 bibtext

### PR DESCRIPTION
**Pull request by stevezac-osu**
- Made minor changes to pagination module
- Added ability to save a bibtext file for publications
- added new filters for base model that do a lower case function call on the searched item and the searchable text
  - likelow - looks for the lower case needle in a lower case haystack (searching allows for case insensitive search)
  - swlow  - if the word starts with (searching allows for case insensitive search)
  - ewlow  - if the word ends with  (searching allows for case insensitive search)
- added pagination to publications
- fixed minor errors

### CODE REVIEW

**Review by nawaji — COMMENTED** [review]
Everything looks great! I'll wait for Ann Marie's review for merging these commits. 
One consideration is potentially including a modal that confirms if the user wants to download the bibtex when they click 'cite'. 

The paper titles link to a URL while 'cite' is a direct download. (Basically, consistency between elements that look similar)

**Comment by stevezac-osu** [comment]
That’s a wonderful idea.  We can either add it to this pull request or in a
later.  Up to you guys

**Comment by stevezac-osu** [comment]
"One consideration is potentially including a modal that confirms if the user wants to download the bibtex."  Why don't you ask during our meeting tomorrow?

**Review by annmariehi — APPROVED** [review]
Looks good to me, we can wait to ask what he thinks but I think what Jonathan suggested is just good UX.

**Pull request merged**
